# Generated by Django 5.1.7 on 2025-04-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_id', models.IntegerField()),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('specilization', models.CharField(max_length=100)),
                ('scheduleDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.IntegerField()),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.DateField(verbose_name='DateOfBirth')),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('Address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_id', models.IntegerField()),
                ('Bill_status', models.CharField(choices=[('D', 'Due'), ('P', 'Paid')], max_length=1)),
                ('Date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_id', models.IntegerField()),
                ('app_Date', models.DateField()),
                ('app_status', models.CharField(choices=[('s', 'shedualed'), ('c', 'canceled')], max_length=1)),
                ('Dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
