# Generated by Django 5.1.7 on 2025-04-15 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_stud_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_contact_no',
            field=models.IntegerField(blank=True, default=datetime.datetime(2025, 4, 15, 12, 58, 55, 657195, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
