# Generated by Django 5.1.7 on 2025-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_stud_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
