# Generated by Django 5.1.7 on 2025-04-15 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(blank=True, default=datetime.datetime(2025, 4, 15, 13, 6, 12, 289644, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
