# Generated by Django 5.1.7 on 2025-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_stud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
