# Generated by Django 5.1.7 on 2025-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_stud_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
