# Generated by Django 5.1.7 on 2025-04-21 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
