# Generated by Django 5.1.7 on 2025-04-21 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolepermission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='user',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
