# Generated by Django 5.1.7 on 2025-04-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_rolepermission_user_rolepermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
            preserve_default=False,
        ),
    ]
