# Generated by Django 5.1.7 on 2025-04-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_permission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
    ]
