# Generated by Django 5.1.7 on 2025-04-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_permission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='user',
        ),
    ]
