# Generated by Django 5.1.7 on 2025-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_recommendedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='recommendedby',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='recommendedby',
        ),
    ]
