# Generated by Django 5.1.7 on 2025-04-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_author_recommendedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='app.author'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='recommendedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publisher'),
        ),
    ]
