# Generated by Django 5.1.7 on 2025-04-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_recommendedby_publisher_recommendedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publisher'),
        ),
    ]
