# Generated by Django 5.1.7 on 2025-04-15 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 4, 15, 10, 30, 40, 140499, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
