# Generated by Django 5.1.7 on 2025-04-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
    ]
