# Generated by Django 5.1.7 on 2025-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
