# Generated by Django 5.1.7 on 2025-04-15 13:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='UID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='stud_contact_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='dep_id',
            field=models.OneToOneField(default=datetime.datetime(2025, 4, 15, 13, 17, 28, 700276, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stud_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UID',
        ),
    ]
