# Generated by Django 5.1.7 on 2025-04-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_id',
            new_name='id',
        ),
    ]
