# Generated by Django 5.1.7 on 2025-04-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_stud_id_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dep_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
